/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitz.hospital.management.system;

/**
 *
 * @author EFE ROBERT
 */
public class AntiNatalRecords extends javax.swing.JFrame {

    /**
     * Creates new form AntiNatalRecords
     */
    public AntiNatalRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ANTI-NATAL RECORDS");
        setPreferredSize(new java.awt.Dimension(1070, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 122, 122));

        jPanel4.setBackground(new java.awt.Color(69, 69, 69));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Anti-Natal");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 30));

        jLabel2.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel2.setText("Navigation");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\EFE ROBERT\\Downloads\\LATEST ICONS\\pregnant_filled.png")); // NOI18N
        jLabel3.setText("Add NEW");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\EFE ROBERT\\Downloads\\LATEST ICONS\\taurus.png")); // NOI18N
        jLabel4.setText("Labour");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(0, 519, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 800));

        jPanel7.setBackground(new java.awt.Color(0, 122, 122));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1250, 50));

        jTabbedPane1.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(35);
        jTable1.setRowMargin(5);
        jScrollPane1.setViewportView(jTable1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 309, 990, 240));

        jLabel6.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel6.setText("Date Of Booking :");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, -1));

        jLabel7.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel7.setText("Card Number :");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 190, -1));

        jLabel8.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel8.setText("Surname :");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 190, -1));

        jLabel9.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel9.setText("Other Names :");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, -1));

        jLabel10.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel10.setText("Patient Number :");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, -1));

        jLabel11.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel11.setText("Special Circumstances :");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, 70));
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1100, 10));

        jLabel12.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel12.setText("Type Of Delivery :");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 250, 100, 20));
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, -1));

        jLabel13.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel13.setText("GA @ Booking :");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 100, 20));

        jTextField7.setBackground(new java.awt.Color(204, 204, 255));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 190, -1));

        jLabel14.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel14.setText("Anti-Natal Code :");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 100, 20));
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 190, -1));

        jLabel15.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel15.setText("Labour :");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 100, 20));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 190, -1));

        jLabel16.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel16.setText("OG / Surgical :");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 100, 20));
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 190, -1));

        jLabel17.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel17.setText("Menarch :");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, 20));
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 190, -1));

        jLabel18.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel18.setText("Menstration Duration :");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 130, 20));
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 190, -1));

        jLabel19.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel19.setText("Previous Surgery :");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 110, 20));
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 190, -1));

        jLabel20.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel20.setText("Previous Medical History :");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 140, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 190, 50));

        jLabel22.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel22.setText("Signatory :");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 60, 20));
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 170, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel5.setText("Analysis");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel24.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel24.setText("Age :");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 20));
        jPanel10.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        jLabel25.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel25.setText("Para :");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));
        jPanel10.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, -1));

        jLabel26.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel26.setText("LCB :");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 30, 20));

        jLabel27.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel27.setText("Gravida :");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 20));
        jPanel10.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));
        jPanel10.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, -1));
        jPanel10.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, -1));

        jLabel28.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel28.setText("EDD :");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 20));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 210, 190));

        jLabel23.setText("Analysis");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, -1, 20));

        jTabbedPane2.addTab("", jPanel8);

        jTabbedPane1.addTab("Anti-Natal Record     ", jTabbedPane2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel29.setText("Examination Date :");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 20));
        jPanel9.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 190, -1));
        jPanel9.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 190, -1));

        jLabel30.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel30.setText("Weight :");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 20));

        jLabel31.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel31.setText("Dedema :");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 20));
        jPanel9.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 190, -1));
        jPanel9.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 190, -1));

        jLabel32.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel32.setText("Presentation :");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        jLabel33.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel33.setText("Lab Examination :");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 20));
        jPanel9.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 190, -1));

        jLabel34.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel34.setText("Ultra  Ssound :");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 80, 20));

        jLabel35.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel35.setText("BPmm :");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 20));
        jPanel9.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, -1));
        jPanel9.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 190, -1));
        jPanel9.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, -1));

        jLabel36.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel36.setText("EGA Week(s) :");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 20));

        jLabel37.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel37.setText("SFH :");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 60, 20));
        jPanel9.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 190, -1));

        jLabel38.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel38.setText("Attitude :");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 60, 20));
        jPanel9.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 190, -1));

        jLabel39.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel39.setText("Temperature :");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 80, 20));
        jPanel9.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 190, -1));

        jLabel40.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel40.setText("P/R :");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 50, 20));
        jPanel9.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 190, -1));

        jLabel41.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel41.setText("Lie :");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 20));
        jPanel9.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 190, -1));

        jLabel42.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel42.setText("Feotal Heart :");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 70, 20));
        jPanel9.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 190, -1));

        jLabel43.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel43.setText("Clinical Info :");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 70, 20));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 190, -1));

        jLabel44.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\EFE ROBERT\\Downloads\\LATEST ICONS\\plus3.png")); // NOI18N
        jLabel44.setText("Add New ");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 90, 20));
        jPanel9.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 190, -1));

        jLabel45.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel45.setText("Signatory :");
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 70, 20));

        jTabbedPane4.addTab("", jPanel9);

        jTabbedPane1.addTab("Examination Update", jTabbedPane4);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 1170, 660));

        jLabel21.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jLabel21.setText("Type Of Delivery :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 250, 100, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1433, 838));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    setExtendedState(AntiNatalRecords.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntiNatalRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntiNatalRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntiNatalRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntiNatalRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AntiNatalRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
