/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitz.hospital.management.system;

/**
 *
 * @author EFE ROBERT
 */
public class PreOperativeChecklist extends javax.swing.JFrame {

    /**
     * Creates new form PreOperativeChecklist
     */
    public PreOperativeChecklist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel37 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRE OPERATIVE CHECKLIST");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 122, 122));

        jPanel4.setBackground(new java.awt.Color(69, 69, 69));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Pre-Operative Checklist");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 690, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 740));

        jPanel7.setBackground(new java.awt.Color(0, 122, 122));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1350, 50));

        jTable3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable3.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable3.setRowHeight(35);
        jTable3.setRowMargin(5);
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 1180, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("Patients Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 204, 0));
        jLabel29.setText("Key -:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jLabel36.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel36.setText("Q2 =  Was Pre-medicant prescribed ?");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 330, 20));

        jLabel38.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel38.setText("Q1 =  Has patient been Assesed by the Anaesthesiologist ?");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 20));

        jLabel39.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel39.setText("Q3 =  If yes, has it been given {Yes/No} any reaction ?");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, 20));

        jLabel40.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel40.setText("Q4 =  Was Blood or Blood product prescribed ?");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 330, 20));

        jLabel41.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel41.setText("Q5 =  If yes, is Blood product available now ?");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 330, 20));

        jLabel42.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel42.setText("Q6 =  If yes, has patient accepted to receive Blood ?");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 330, 20));

        jLabel43.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel43.setText("Q7 =  Are patient(s) Labouratory results Available ?");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 330, 20));

        jLabel44.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel44.setText("Q9 =  Is patient Starved appriopraitely ?");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 330, 20));

        jLabel45.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel45.setText("Q8 =  Has informed consent been taken and form signed ?");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 330, 20));

        jComboBox1.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, -1));

        jComboBox2.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 50, -1));

        jComboBox3.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 50, -1));

        jComboBox4.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 50, -1));

        jComboBox5.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 50, -1));

        jComboBox6.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 50, -1));

        jComboBox7.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 50, -1));

        jComboBox8.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 50, -1));

        jComboBox10.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 50, -1));

        jLabel46.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel46.setText("Q10 =  Is Patient shaved ?");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 330, 20));

        jLabel47.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel47.setText("Q11 =  Is Patient changed into Operating Theatre outfit ?");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 330, 20));

        jLabel48.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel48.setText("Q12 =  Are patients Vital signs checked and recorded ?");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 330, 20));

        jLabel49.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel49.setText("            instruments, Drapes e.t.c   Ready ?");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 330, 20));

        jLabel50.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel50.setText("Q14 =  Has the patient Dentures ?");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 330, 20));

        jLabel51.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel51.setText("Q15 =  Has it been removed ?");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 330, 20));

        jLabel52.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel52.setText("Q16 =  Has the patient jewlery been removed ?");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 330, 20));

        jLabel53.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel53.setText("Q17 =  Has catether been passed ?");
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 330, 20));

        jComboBox9.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, 50, -1));

        jComboBox12.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 50, -1));

        jComboBox13.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 50, -1));

        jComboBox14.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 50, -1));

        jComboBox15.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 50, -1));

        jComboBox16.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, 50, -1));

        jComboBox17.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, 50, -1));

        jComboBox18.setFont(new java.awt.Font("Narkisim", 0, 12)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 50, -1));

        jLabel54.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel54.setText("Q13 =  Are all pre-operative request e.g Drugs, Fluids,");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 330, 20));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 1180, 310));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel28.setText("Surname :");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 60, 20));
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, -1));

        jLabel58.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel58.setText("Patient Number :");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, -1));
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, -1));

        jLabel30.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel30.setText("Proposed Surgery :");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 110, 20));
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 200, -1));

        jLabel31.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel31.setText("Checked by :");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 90, 20));
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, -1));
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 200, -1));

        jLabel32.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel32.setText("Age :");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 60, 20));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 200, -1));

        jLabel33.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel33.setText("Blood Group :");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 80, 20));

        jLabel34.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel34.setText("Employee NO. :");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 90, 20));
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 200, -1));

        jLabel35.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel35.setText("Date :");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 40, 20));
        jPanel8.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 200, -1));

        jLabel37.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel37.setText("Other Names :");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 1180, 140));

        jLabel55.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon("C:\\Users\\EFE ROBERT\\Downloads\\LATEST ICONS\\save2.png")); // NOI18N
        jLabel55.setText("Save");
        jLabel55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1414, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(PreOperativeChecklist.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreOperativeChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreOperativeChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreOperativeChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreOperativeChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreOperativeChecklist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
